wandb_version: 1

batch_size:
  desc: null
  value: 16
num_epochs:
  desc: null
  value: 25
lr:
  desc: null
  value: 0.0001
seq_len:
  desc: null
  value: 350
d_model:
  desc: null
  value: 512
lang_src:
  desc: null
  value: en
lang_tgt:
  desc: null
  value: it
tokenizer_file:
  desc: null
  value: tokenizer_{0}.json
device:
  desc: null
  value: cuda
wb:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.17.2
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1737242391
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.5
      5: 0.17.2
      6: 4.32.1
      8:
      - 3
      - 5
      - 13
      13: windows-amd64
